### ISSUE TITLE
including props file with $(SolutionDir) macro issue

### ISSUE THREAD

**Issue by peteer22r** [liamkf/msfastbuild#13]
When I try to build project that includes props file with path containing  macro $(SolutionDir), build fails with following message:

```
Launching msfastbuild with command line: -s "D:\Dev\Tests\FastBuildTest\FastBuildTest.sln" -c Debug -f x86 -a"-dist -ide" -b "D:\Dev\Tools\FASTbuild\fbuild.exe"
Exception loading project D:\Dev\Tests\FastBuildTest\FastBuildTest\FastBuildTest.vcxproj exception The imported project "D:\Dev\Tests\FastBuildTest\FastBuildTest\PropertySheet.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\Dev\Tests\FastBuildTest\FastBuildTest\FastBuildTest.vcxproj
0/0 built.
```

When props file is included with relative path
 like this:
`<Import Project="..\PropertySheet.props" />`
It works. But when including with abosule path that contains macro it dose not work:
`<Import Project="$(SolutionDir)\PropertySheet.props" />`

Minimal project for reproducing issue:
[FastBuildTest.zip](https://github.com/liamkf/msfastbuild/files/504879/FastBuildTest.zip)

**Comment by peteer22r** [comment]
I've traced it to:

```
        static public void EvaluateProjectReferences(...)
        {
            // ...
                ProjectCollection projColl = new ProjectCollection();
                                // ...
                        Project proj = projColl.LoadProject(ProjectPath); // << here
```

Exception is thrown from within:
    Microsoft.Build.dll!Microsoft.Build.Evaluation.ProjectCollection.LoadProject(string fileName)

I guess we can't do much about this one :(
Project is fine because it's build via msbuild and VS IDE.

**Comment by liamkf** [comment]
Hi, thanks for the report and minimal repro project! 

It seems to have been a matter of just making sure the ProjectCollection had the SolutionDir property set properly on it. I've done that in the latest and it seems to fix it right up. Please let me know if it fixes the issue for you! :)

**Comment by peteer22r** [comment]
Hi. Grate, I've tested it (finally) and it's better. Described error is gone. 

Unfortunately something else fails, I get only message build 2/x projects. I guess build stops due to some error, but there is not output. I'll try to pin point the issue and maybe issue a new issue :)

ps. Sorry for so long delay.

**Comment by liamkf** [comment]
No worries! Let me know if you find out more about the new problem (sounds mysterious!), I'd be happy to help if I can as well! :)

**Comment by Domain** [comment]
The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
