### ISSUE TITLE
missing build log 

### ISSUE THREAD

**Issue by peteer22r** [liamkf/msfastbuild#14]
Hi

I have a project that fails while building with msfastbuild. There isn't any information why. 
While building with normal build it's ok. 

Is it possible to turn on some detailed output?

**Comment by liamkf** [comment]
Hi there! Sorry about the delay! 

There's no detailed output available right now, although that could certainly be something to add. Is it generating a bff file for the vcproj, or having problems before that happens? If it is I would try running the bff file it generates with fastbuild directly and see what happens. If it's not... you can either try to run it in the debugger, or if you can share the vcxproj I'll have a look when I have time and try to see what's going wrong! :)

**Comment by peteer22r** [comment]
I run bff directly. It also wont build. Some linkage errors. I'll try to prepare a minimal repro. Or I'll just trace what dependency is missing (pragma comment, vcxporj propety, or watherer).

Regarding output. Direct output from fastbuild could be shown in new output tab next to current one. It could also be configurable in settings.

**Comment by liamkf** [comment]
Hmm any clues as to what was going wrong here? I'm just piping the output from fbuild straight through to the window as is, so if it's not giving anything in the current window, I think I'd have to try to determine that something is wrong with the fbuild path setup.

**Comment by peteer22r** [comment]
When I call fastbuild on solution in IDE I get output like this:
`Launching msfastbuild with command line: -s "d:\path\to\my.solution.sln" -c Debug -f x64 -a"-ide" -b "D:\tools\dev\fastbuild\FBuild.exe"
Building some.project1
Building some.project2
Building some.project3
Building some.project4
Building some.project5
Building some.project6
5/327 built.`

I have following settings:
![image](https://cloud.githubusercontent.com/assets/2303799/23742259/73bc7944-04ac-11e7-8019-8a47fb60c33d.png)

Beside this, I don't have any other output. No errors, no warnings.
Using msfastbuild from command line give me more verbose output with error that caused build to fail.

Maybe You could add a setting set select verbosity level?

About my initial error, in fastbuild scripts I see that project 6 don't have depended library passed to linker (project 5). But I couldn't create minimal repro. 

Small project with just two libraries works almost fine. One problem I found that when calling msfastbuild with -a"-ide" project failed because it had spaces in it's path.

**Comment by peteer22r** [comment]
As for my link issue, it seems that this pull request would fix it: https://github.com/liamkf/msfastbuild/pull/19 
As I checked, ReferenceOutputAssembly with false was automatically added while conversion from VS 2008.

Either way, Normal Build in Visual Studio build it without an issue so it would be nice if msfastbuild would also work :)
