### ISSUE TITLE
Can't compile with non English Visual Studio installation

### ISSUE THREAD

**Issue by jairbubbles** [liamkf/msfastbuild#2]
I had that error when compiling freetype but I had it with other projects too:

`2> Error: opening file 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\1033\clui.dll' in Compiler ToolManifest`

Do you hard code all system files in msfasbuild or do you have a way to ask Visual Studio to get tem ? Maybe they are slightly differents with Commuinty edition.

**Comment by liamkf** [comment]
Yes that is an unfortunate result of my not finding a good way to detect which languages are installed with Visual Studio, so instead it's hardcoded to use English.

I'm using the Community edition as well, but the 1033 is the en-US localization, I'm guessing you instead have 1036 for the french language pack. It's definitely annoying (there's a similar issue [here ](https://github.com/liamkf/Unreal_FASTBuild/issues/2)) and I'm open to suggestions about a good way to detect what's installed! FASTBuild when building itself also uses only the 1033 clui.dll, but it seems like there should be a better way to detect what's needed.

**Comment by jairbubbles** [comment]
Yes you're right I'm in french at home and that's terrible to use when you're used to english. I plan to change that and that kind of fix the issue :-D

Anyway, this could be a warning when -dist is not used.

Why don't you parse the folder and get the first clui.dll you find ? It would be better to check some registry key but it might take a long time to find out which one.

**Comment by jairbubbles** [comment]
It seems you can install several language packs at the same time.
French is here for instance: https://www.microsoft.com/fr-fr/download/details.aspx?id=48157

I'm installing english right now and see if I can find some interesting registrey keys.

**Comment by jairbubbles** [comment]
After one Visual Studio installation corruption I was able to find the registrey key using [procmon ](https://technet.microsoft.com/en-US/sysinternals/processmonitor.aspx):

![2016-09-12 20_29_53-clipboard](https://cloud.githubusercontent.com/assets/15875066/18447618/b1005e4e-7927-11e6-8c27-864b6f77b126.png)

Hope it helps you !

**Comment by liamkf** [comment]
Ahhh there it is! Awesome! I just submitted a change that uses that registry value to find the clui.dll, I did not install a different language pack, but it seems like it should work. I'll do the same thing for the Unreal_FASTBuild project which is great!

Thanks for digging it up! :)

**Comment by jairbubbles** [comment]
Well it doesn't seem that easy.

I was able to change language to English hence the 1033 in the registry but the 1033 folder doesn't contain a clui.dll file.

If I switch back to french it should work but what we need is "the installation language registry key".

**Comment by jairbubbles** [comment]
Maybe we'd better look into cl.exe directly. It's not related to Visual Studio language even if both languages should be the same after a fresh install.

I'll check on my home pc but maybe the language in the dll is a good starting point:
![2016-09-13 10_21_12-proprietes de _ cl exe](https://cloud.githubusercontent.com/assets/15875066/18466412/e9b4cb48-799b-11e6-8919-c8eab4e05a72.png)

In C# you should be able to get it with:
`System.Diagnostics.FileVersionInfo.GetVersionInfo`

**Comment by liamkf** [comment]
Ah darn, I guess I was being optimistic... :) 

I would suspect that cl.exe will always be in English though no?

**Comment by jairbubbles** [comment]
The answer in a few hours when I'll be at home... not easy to find a french visual installation at work :-D

**Comment by jairbubbles** [comment]
Well the answer is "English too" :-(

After some more testing it seems the dll is dynamically loaded by parsing the sub folders for a file named clui.dll. 
If I rename the folder 1036 to something else the build is successful.
I I rename clui.dll to something else the build fails.

I guess you'll have  to do the same in C# to mimic that behavior.

**Comment by liamkf** [comment]
Haha, oy, that seems a bit crazy! I had a quick look through the msbuild source to see if there was anything good to go on without luck. So I've done as you suggested and just searched around for a clui.dll in numeric folders in the bin directory. Which seems to work in my "renaming the 1033" folder tests... :D please let me know how it goes!

**Comment by jairbubbles** [comment]
Works ok with version 0.18.

I have the includes showing up in the log though :

```
Remarqueÿ: inclusion du fichierÿ:  C:\Users\Julien\Desktop\Code\freetype-2.7\include\ft2build.h
Remarqueÿ: inclusion du fichierÿ:   C:\Users\Julien\Desktop\Code\freetype-2.7\include\freetype/config/ftheader.h
```

**Comment by liamkf** [comment]
Hmm does it have /showincludes on the command line? I don't think that's coming from msfastbuild! :)

**Comment by jairbubbles** [comment]
No I don't think so. Nothing in the output with a VS build.

**Comment by jairbubbles** [comment]
I'm closing this one as it's another issue.
