### ISSUE TITLE
add unreal engine build support?

### ISSUE THREAD

**Issue by molixiaoge** [liamkf/msfastbuild#21]
Unreal engine source is so big,which build is so dispirited!So do you want to support it?

**Comment by liamkf** [comment]
Hi there! Sorry for the delay in responding! 

The Unreal engine has its own build dependency checker and unity file creation in the UnrealBuildTool, and doesn't use the msbuild system, so msfastbuild is not really attempting to solve that problem. 

That being said we have spent some time on some code to generate workable fastbuild configuration files [here](https://github.com/liamkf/Unreal_FASTBuild), but its benefits mainly come from allowing the distribution of the build over the network as well as taking advantage of the fastbuild cache.

Cheers,
Liam
