### ISSUE TITLE
project path contains space char bug?

### ISSUE THREAD

**Issue by molixiaoge** [liamkf/msfastbuild#22]
Hi,when i create a project(ConsoleApplication10) and right click fastbuild menu then i find output shows noting to build!

ConsoleApplication10 Project Path: 

> C:\Users\Administrator\Documents\Visual Studio 2015\Projects\ConsoleApplication10\ConsoleApplication10

ConsoleApplication10 project output shows:

> Building ConsoleApplication10.vcxproj Debug x86
> Launching msfastbuild with command line: -p "ConsoleApplication10.vcxproj" -c Debug -f x86 -s "C:\Users\Administrator\documents\visual studio 2015\Projects\ConsoleApplication10\ConsoleApplication10.sln" -a"-dist -ide" -b "F:\toolbin\fbuild.exe"
> Building ConsoleApplication10
> 0/1 built.

And then,i doubt if the path contains space,so i create another project(ConsoleApplication1) without any space in path.I click fastbuild menu ,then everything is ok!

ConsoleApplication1 Project Path: 

> C:\Users\Administrator\Documents\Projects\ConsoleApplication1\ConsoleApplication1

ConsoleApplication1 project output shows:

> Building ConsoleApplication1.vcxproj Debug x86
> Launching msfastbuild with command line: -p "ConsoleApplication1.vcxproj" -c Debug -f x86 -s "c:\users\administrator\documents\Projects\ConsoleApplication1\ConsoleApplication1.sln" -a"-dist -ide" -b "F:\toolbin\fbuild.exe"
> Building ConsoleApplication1
> 1/1 built.
> 

So,I doubt if it is a bug?Project path cannot contains space char?

**Comment by liamkf** [comment]
Hi there! I think that might be the same issue mentioned here: https://github.com/liamkf/msfastbuild/issues/3 which is a minor bug in fastbuild. That being said it looks like the fix may have gotten lost in the shuffle, so when I get some time to get back into this and look at it I'll try to make sure it gets included in the next release of fastbuild!

In the meantime if it's a blocker for you, you should be able to apply the fix I mention in the linked issue to fastbuild and it should fix your problem. :)

**Comment by molixiaoge** [comment]
I will read the issue.Thxs,for your reply!
