### ISSUE TITLE
can not recorgnize rc.exe

### ISSUE THREAD

**Issue by wony-zheng** [liamkf/msfastbuild#28]
when i use msfastbuild to build vc.project. it output this error. and this rc.exe is a valid in command line.
I edit the `XXXXXXX.vcxproj_Debug_Win32.bff` change the `x64` to `x86`, and this samle error occur.
```
XXXXXXX.vcxproj_Debug_Win32.bff(41,1): FASTBuild Error #1500 - Compiler() - Compiler detection failed. Unrecognized executable 'C:\Program Files (x86)\Windows Kits\8.1\bin\x64\rc.exe'.
Compiler('rc') { .Executable = '$WindowsSDKBasePath$\bin\x64\rc.exe' }
^
\--here
0/11 built.
```

**Comment by mayenjoy** [comment]
the same as you

**Comment by iobzo** [comment]
just add 'custom' like this:
```
Compiler('rc')
{
	.Executable = '$WindowsSDKBasePath$\bin\x86\rc.exe'
	.CompilerFamily = 'custom'
}
```

**Comment by liamkf** [comment]
Yes as iobzo mentioned this is due to changes in newer versions of fastbuild. You can fix it as he mentioned or use an older version.
