### ISSUE TITLE
Custom build steps are not handled

### ISSUE THREAD

**Issue by tethysm** [liamkf/msfastbuild#31]
I found while using the msfastbuild utility that custom build steps, such as build-time file generation steps, were not being handled. I've modified the code for msfastbuild in the attached zip file so that it takes custom build steps and places them in a batch file to be executed before the main build sequence begins. I have tried pushing my changes to a branch, but have been unsuccessful so far due to permission issues - so this was the next best option. If possible, please give me permission to push to the repo so I can create a PR with my changes, thank you!
[msfastbuild.zip](https://github.com/liamkf/msfastbuild/files/2321969/msfastbuild.zip)

**Comment by cfers** [comment]
my qt project (Custom build steps:moc.exe  rcc.exe uic.exe) does not work with your modified vsix![msfastbuild.zip](https://github.com/liamkf/msfastbuild/files/2321969/msfastbuild.zip)

**Comment by liamkf** [comment]
Hi mannj1, apologies for the long delay! Thanks for investigating and for your fix. I think if your fix has been maintained having it in your own fork is likely the best way going forward! Cheers.
