### ISSUE TITLE
Charset issue with non english compiler 

### ISSUE THREAD

**Issue by jairbubbles** [liamkf/msfastbuild#5]
MSBuild output :
`1>c:\users\julien\desktop\code\freetype-2.7\src\psaux\t1decode.c(1360): warning C4267: '=' : conversion de 'size_t' en 'FT_Int', perte possible de données (compilation du fichier source ..\..\..\src\psaux\psaux.c)`

While FBuild output:
`c:\users\julien\desktop\code\freetype-2.7\src\type1\t1driver.c(264): warning C4267: '='ÿ: conversion de 'size_t' en 'FT_ULong', perte possible de donn‚es`

(might be a FastBuild issue though)

**Comment by liamkf** [comment]
Hmm, if you call fbuild with the bff generated for Freetype does it give the same output? I'm really just passing through the unadorned output of fbuild so I'd be surprised if the locale in msfastbuild is the issue, but if it is I'd be happy to muck with it... :D

**Comment by jairbubbles** [comment]
Well when calling:
`fbuild -config freetype.vcxproj_Debug_x64.bff -clean`
I get the right output:
`c:\users\julien\desktop\code\freetype-2.7\src\psaux\t1decode.c(1360): warning C4267: '=' : conversion de 'size_t' en 'FT_Int', perte possible de données`

I had the issue with a C# tool, the charset used byt the console is very special. I'll send you the snippet when I'll be at home. It might help you out.

**Comment by jairbubbles** [comment]
On my project when launching a process I add the following lines:
`m_processStartInfo.StandardOutputEncoding = System.Text.Encoding.GetEncoding("ibm850"); // Western European (DOS), type chcp in command line you should see 850 !`

The current value is also visible in cmd properties:
![cmd_properties](https://cloud.githubusercontent.com/assets/15875066/18542491/807c58da-7b2b-11e6-8b73-33f4194f3565.png)

Maybe it's not a good fix as it's too specific to french systems but it might be a good starting point. I don't understand why it doesn't use the default value.

**Comment by liamkf** [comment]
Hmm, when I put this line:
`FBProcess.StartInfo.StandardOutputEncoding = Console.OutputEncoding;`

I get ibm850 as the default... which seems odd! I guess your default Console.OutputEncoding is not ibm850 for some reason? Are you on Windows 10? Because it seems like the default for me I'm not opposed to just forcing it to ibm50, but I'd be curious what you think!

**Comment by jairbubbles** [comment]
I'm on windows 10 yes.

When reading your code it doesn't sound too stupid. "I'm forcing the standard output to use console encoding"
Did you release one version with that line of code ?

**Comment by liamkf** [comment]
No, but I'll include it in my next release for you to try! :)

**Comment by liamkf** [comment]
Ok, it's in the latest!

**Comment by jairbubbles** [comment]
Well it does not fix the issue. I'll look into it. It will be easier for me to try directly different values and check if it fixes the issue.

**Comment by jairbubbles** [comment]
By looking at the code it seems you launch msfastbuild.exe which launches fastbuild.exe. You might do the same trick in the vsix project where you put the comment "Launching msfastbuild with command line: ".

Anyway I can't install VS so I can't test neither :-S

**Comment by jairbubbles** [comment]
I finally fix it after resetting my windows 10 installation :-D

**Comment by liamkf** [comment]
Ok hopefully the latest fixes this up! :)

**Comment by liamkf** [comment]
I'm hoping it caught all of these... :) Let me know if I didn't!
